### ISSUE TITLE
Way to specify file extension of temporary file

### ISSUE THREAD

**Issue by rossmacarthur** [milkey-mouse/edit#1]
Hi :wave: thanks for creating this crate. I'm planning on using it in [a project of mine](https://github.com/rossmacarthur/sheldon). I would love if there was a way to specify the extension (or suffix) of the temporary file that is created when you call `edit::edit`. This would be useful because then syntax highlighting would work on the opened file.

I was imagining a basic API like

```rust
edit::edit_with_suffix(text, "toml")
```

or

```rust
edit::edit_with_extension(text, "toml")
```

**Comment by twilligon** [comment]
It would be pretty easy to copy what [`edit_bytes`](https://github.com/milkey-mouse/edit/blob/869b597a40e16b104bcd4f2a5375847e746ff59d/src/lib.rs#L187) is doing but with your own `NamedTempFile`, something like this:

```rust
let mut file = Builder::new()
    .suffix(".toml")
    .tempfile()?;
file.write(buf.as_ref())?;

let path = file.into_temp_path();
edit_file(&path)?;

let edited = fs::read(&path)?;

path.close()?;
```

It's [slightly more annoying](https://github.com/milkey-mouse/edit/blob/869b597a40e16b104bcd4f2a5375847e746ff59d/src/lib.rs#L168) if you also want to convert to a UTF-8 string.

I'd be open to adding a function for this specific use case, like `edit` but taking a `NamedTempFile` as an argument; then the user can specify the directory, prefix, suffix, etc. with a [`tempfile::Builder`](https://docs.rs/tempfile/3.1.0/tempfile/struct.Builder.html).

On another note, if you're parsing TOML files (or any format supported by `serde`, in principle) with `edit`, I've written some code for validation with serde (both syntax-wise and for a specific config) and user-friendly in-editor syntax errors for [another project of mine](https://github.com/milkey-mouse/storm/blob/master/src/config.rs) that could definitely be reused. (run `storm config` for a demo). I'm looking into refactoring this into its own crate (`edit_toml`?) but I haven't gotten around to it yet (and the implementation for `storm` isn't 100% complete).

**Comment by Gottox** [comment]
I like to have this too :)

**Comment by Gottox** [comment]
Implement the feature. Please give feedback :)

```toml
edit = { git = "https://github.com/Gottox/edit.git", branch = "tempfile_builder" }
```

**Comment by twilligon** [comment]
[Fixed](https://docs.rs/edit/0.1.2/edit/fn.edit_with_builder.html) in [v0.1.2](https://github.com/milkey-mouse/edit/releases/tag/v0.1.2).
