### ISSUE TITLE
Remove src/bin.rs when releasing to cargo

### ISSUE THREAD

**Issue by jbtrystram** [milkey-mouse/edit#7]
Releasing the example file to cargo create additionnal un-necessary steps when one want to package the library for a linux distribution. It also increase the size of the crate for no reason.

**Comment by twilligon** [comment]
It should increase the size of the crate by less than a kilobyte, so I'm not too worried about what it does to download size. Could you go into more detail about the problems/unnecessary steps the example creates when packaging this library?

**Comment by jbtrystram** [comment]
I am using your crate as a library for my app that I want to package in fedora. So as it's a dependency it needs to be packaged as well. The `bin.rs` result in an executable in the package. It's doesn't really make sense to install a "hello world" binary on someone machine just to get the library does-it ? 
I started the package process anyway (https://gitlab.com/jbtrystram/rust-edit) with a patch to remove the bin file but it's a bit of a pain to maintain, for something that does not have a lot of sense in the crate anyway.
